services:
  front-builder:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app
    command: tail -f /dev/null
    # command: sh -c "yes | npm install -y; npx run build; npm run build"
    # command: npm install @capacitor/core @capacitor/cli @capacitor/android
    # command: npm install @radix-ui/react-accordion @radix-ui/react-alert-dialog @radix-ui/react-dropdown-menu @radix-ui/react-dialog @radix-ui/react-popover @radix-ui/react-progress @radix-ui/react-switch @radix-ui/react-tabs @radix-ui/react-tooltip @radix-ui/react-slider @radix-ui/react-toast @radix-ui/react-toggle-group @radix-ui/react-radio-group @radix-ui/react-menubar @radix-ui/react-collapsible @radix-ui/react-hover-card @radix-ui/react-separator @radix-ui/react-select @radix-ui/react-scroll-area @radix-ui/react-navigation-menu @radix-ui/react-context-menu @radix-ui/react-aspect-ratio @radix-ui/react-avatar
    # command: npm install react-day-picker@8.10.1 recharts@2.12.7 react-resizable-panels@2.0.19 --legacy-peer-deps