services:
  food-detector:
    build: food-detector
    container_name: food-detector
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://admin:secret@mongo:27017/mydb?authSource=admin
    volumes:
      - ./food-detector:/app
    networks:
      - health-ai

  account:
    build: account
    container_name: account
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://admin:secret@mongo:27017/healthai?authSource=admin
      - JWT_SECRET=healthai_secret
    networks:
      - health-ai

  mongo:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: healthai
    networks:
      - health-ai

volumes:
  mongo_data:

networks:
  health-ai:
    driver: bridge
